### PR TITLE
Adding no-op support, automatic oauth tokens, and error handling.

### PR DESCRIPTION
**Pull request by zenspider**

### CODE REVIEW

**Comment by zenspider** [comment]
Also, I'm filing a bug (via @tenderlove) to get `not:locked` and `is:locked` query support added.

**Comment by zenspider** [comment]
HOLY CRAP I JUST LOCKED 647 ISSUES ON MINITEST

**Comment by presidentbeef** [comment]
I *knew* there must be other people out there who wanted this functionality. :smile:

**Comment by presidentbeef** [comment]
Hrmmm reading the token from the file will be messed up if an age option is passed in...might have to switch to real option parsing.

**Comment by presidentbeef** [comment]
Released as-is for now.

**Pull request merged**
